"""add_lesson_discussions

Revision ID: 03676ac0ebf4
Revises: d30590b3b744
Create Date: 2026-04-14 04:54:44.015895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '03676ac0ebf4'
down_revision: Union[str, None] = 'd30590b3b744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_discussions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_discussions_lesson_id'), 'lesson_discussions', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_discussions_user_id'), 'lesson_discussions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_discussions_user_id'), table_name='lesson_discussions')
    op.drop_index(op.f('ix_lesson_discussions_lesson_id'), table_name='lesson_discussions')
    op.drop_table('lesson_discussions')
    # ### end Alembic commands ###