"""add_session_attendance_table

Revision ID: 29ea9b602666
Revises: fddc2ad09f96
Create Date: 2026-04-12 19:49:00.386606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '29ea9b602666'
down_revision: Union[str, None] = 'fddc2ad09f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('live_session_id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.String(length=50), nullable=True),
    sa.Column('left_at', sa.String(length=50), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['live_session_id'], ['live_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_attendances_id'), 'session_attendances', ['id'], unique=False)
    op.drop_index('ix_session_attendance_id', table_name='session_attendance')
    op.drop_table('session_attendance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_attendance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_at_join', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('attendance_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('left_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], name='session_attendance_session_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='session_attendance_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='session_attendance_pkey'),
    sa.UniqueConstraint('session_id', 'user_id', name='uq_session_attendance_user')
    )
    op.create_index('ix_session_attendance_id', 'session_attendance', ['id'], unique=False)
    op.drop_index(op.f('ix_session_attendances_id'), table_name='session_attendances')
    op.drop_table('session_attendances')
    # ### end Alembic commands ###