"""class user fix

Revision ID: 2b78f4cc5735
Revises: 77655e69790d
Create Date: 2026-03-19 04:27:42.836247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '2b78f4cc5735'
down_revision: Union[str, None] = '77655e69790d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###