"""add_password_reset_fields_to_users

Revision ID: 47aa2d16d290
Revises: 117b01714521
Create Date: 2026-04-15 03:53:43.875707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '47aa2d16d290'
down_revision: Union[str, None] = '117b01714521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###