"""add search and discovery core

Revision ID: 4c1de676a3d5
Revises: 604126947acd
Create Date: 2026-03-09 16:25:44.863740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '4c1de676a3d5'
down_revision: Union[str, None] = '604126947acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_lessons_lesson_type'), 'lessons', ['lesson_type'], unique=False)
    op.create_index(op.f('ix_lessons_status'), 'lessons', ['status'], unique=False)
    op.create_index(op.f('ix_lessons_visibility'), 'lessons', ['visibility'], unique=False)
    op.create_index(op.f('ix_live_sessions_session_type'), 'live_sessions', ['session_type'], unique=False)
    op.create_index(op.f('ix_live_sessions_status'), 'live_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_posts_post_type'), 'posts', ['post_type'], unique=False)
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    op.create_index(op.f('ix_posts_visibility'), 'posts', ['visibility'], unique=False)
    op.create_index(op.f('ix_quizzes_assessment_type'), 'quizzes', ['assessment_type'], unique=False)
    op.create_index(op.f('ix_quizzes_status'), 'quizzes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quizzes_status'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_assessment_type'), table_name='quizzes')
    op.drop_index(op.f('ix_posts_visibility'), table_name='posts')
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_index(op.f('ix_posts_post_type'), table_name='posts')
    op.drop_index(op.f('ix_live_sessions_status'), table_name='live_sessions')
    op.drop_index(op.f('ix_live_sessions_session_type'), table_name='live_sessions')
    op.drop_index(op.f('ix_lessons_visibility'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_status'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_lesson_type'), table_name='lessons')
    # ### end Alembic commands ###