"""add media management core

Revision ID: 604126947acd
Revises: 790e84c2e96e
Create Date: 2026-03-09 14:38:21.942736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '604126947acd'
down_revision: Union[str, None] = '790e84c2e96e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('bucket_name', sa.String(length=100), nullable=True),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_extension', sa.String(length=20), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('media_type', sa.String(length=30), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=128), nullable=True),
    sa.Column('public_url', sa.Text(), nullable=True),
    sa.Column('relative_path', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_media_files_entity_id'), 'media_files', ['entity_id'], unique=False)
    op.create_index(op.f('ix_media_files_entity_type'), 'media_files', ['entity_type'], unique=False)
    op.create_index(op.f('ix_media_files_id'), 'media_files', ['id'], unique=False)
    op.create_index(op.f('ix_media_files_media_type'), 'media_files', ['media_type'], unique=False)
    op.create_index(op.f('ix_media_files_mime_type'), 'media_files', ['mime_type'], unique=False)
    op.create_index(op.f('ix_media_files_owner_id'), 'media_files', ['owner_id'], unique=False)
    op.add_column('lesson_resources', sa.Column('media_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lesson_resources', 'media_files', ['media_file_id'], ['id'], ondelete='SET NULL')
    op.add_column('post_attachments', sa.Column('media_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post_attachments', 'media_files', ['media_file_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_attachments', type_='foreignkey')
    op.drop_column('post_attachments', 'media_file_id')
    op.drop_constraint(None, 'lesson_resources', type_='foreignkey')
    op.drop_column('lesson_resources', 'media_file_id')
    op.drop_index(op.f('ix_media_files_owner_id'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_mime_type'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_media_type'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_id'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_entity_type'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_entity_id'), table_name='media_files')
    op.drop_table('media_files')
    # ### end Alembic commands ###