"""class user fix

Revision ID: 77655e69790d
Revises: cf0ca16acb0f
Create Date: 2026-03-18 14:58:55.366755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '77655e69790d'
down_revision: Union[str, None] = 'cf0ca16acb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###