"""add_cover_url_to_user_profile

Revision ID: 77b7711cb2f1
Revises: 41baaa879b6a
Create Date: 2026-04-13 02:26:28.616677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '77b7711cb2f1'
down_revision: Union[str, None] = '41baaa879b6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('cover_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'cover_url')
    # ### end Alembic commands ###