"""add_created_by_to_subjects

Revision ID: 96c2eafbd6e6
Revises: f2a8c1c423ff
Create Date: 2026-04-15 02:41:28.820376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '96c2eafbd6e6'
down_revision: Union[str, None] = 'f2a8c1c423ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###