"""add_lesson_discussions

Revision ID: c1737f27934a
Revises: 77b7711cb2f1
Create Date: 2026-04-14 03:50:47.821963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'c1737f27934a'
down_revision: Union[str, None] = '77b7711cb2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###