"""update class member relationships

Revision ID: cf0ca16acb0f
Revises: 89d3111a46ea
Create Date: 2026-03-13 17:46:21.952867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'cf0ca16acb0f'
down_revision: Union[str, None] = '89d3111a46ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_class_members_class_id'), 'class_members', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_members_learner_id'), 'class_members', ['learner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_members_learner_id'), table_name='class_members')
    op.drop_index(op.f('ix_class_members_class_id'), table_name='class_members')
    # ### end Alembic commands ###