"""add_lesson_discussions_table

Revision ID: d30590b3b744
Revises: c1737f27934a
Create Date: 2026-04-14 04:52:05.026561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'd30590b3b744'
down_revision: Union[str, None] = 'c1737f27934a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###