"""add_created_by_to_subjects

Revision ID: f2a8c1c423ff
Revises: 03676ac0ebf4
Create Date: 2026-04-14 14:48:52.498508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'f2a8c1c423ff'
down_revision: Union[str, None] = '03676ac0ebf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###