"""add_reset_token_to_users

Revision ID: ffa3c6ae3832
Revises: 47aa2d16d290
Create Date: 2026-04-15 04:02:54.835828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'ffa3c6ae3832'
down_revision: Union[str, None] = '47aa2d16d290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###